#!/usr/bin/env bash
# script that transfers a file from client to server


if [[ -z "$3" ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi
scp -i "$4" -o StrictHostKeyChecking=No "$1" "$3@$2":~/
