#!/usr/bin/env bash
# nginx install
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
