#!/usr/bin/env bash
# nginx install
# The redirection must be a "301 Moved Permanently"
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School'> /var/www/html/index.html
sed -i "19i\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t" /etc/nginx/sites-available/default
sudo service nginx start
