#!/usr/bin/env bash
# nginx install
# The redirection must be a "301 Moved Permanently"

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "19i\\\tlocation /redirect_me {\n\t\terror_page 404 =301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default
service nginx start
