#!/usr/bin/env bash
# nginx install
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School'> /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i "19i\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default
sed -i "22i\\\terror_page 404 /404.html;\n\tlocation /404 {\n\\troot /usr/share/nginx/html;\n\\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo service nginx start
