#!/usr/bin/env bash
# Not found page 404

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
	root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        location /redirect_me {
                error_page 404 =301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;

        location =/404.html {
                root /var/www/html/;
        }
}" > /etc/nginx/sites-available/default
service nginx start
