#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install haproxy
sudo sed -i "22i\frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n" /etc/haproxy/haproxy.cfg
sudo sed -i "27i\backend http_back\n\tbalance roundrobin\n\tnode http\n\tserver 1414-web-01 34.74.253.204:80 check\n\tserver 1414-web-02 34.75.174.79:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
