#!/usr/bin/env bash
# Install / Configure HAproxy on your lb-01 server

apt-get update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.6
apt-get install -y haproxy=1.6.\*

# Enable HAProxy to be started by the init script
printf "%s\n" "ENABLED=1" >> /etc/default/haproxy

# Distribute requests using a roundrobin algorithm
printf "%s\n"\ "
frontend www.meddebmoussadak.tech
        bind *:80
        mode http
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 1414-web-01 35.237.13.104:80 check
        server 1414-web-02 35.231.190.248:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
