#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, but for the 4th
#iteration is displaying "bad luck" and in 8th iteration is displaying
# "good luck"

i=1
while [ $i -le 10 ]
do
if [ $i == 4 ]; then
    echo "bad luck"
elif [ $i == 8 ];then
    echo "good luck"
else
    echo "Holberton School"
fi
i=$(( i + 1))
done