#!/usr/bin/env bash
# Run Nginx as Nginx 
chmod 600 /etc/nginx/nginx.conf
pkill apache2
pkill nginx
sed -i "s/#user.*/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
service nginx start
